### ISSUE TITLE
EPIC: Make Chrome Store Ready

### ISSUE THREAD

**Issue by williamspiro** [williamspiro/HubSpot-Developer-Extension#10]
We need to make some changes to make sure this is safe to use publicly and in the Chrome store:

- [x] Change the extension icon, see https://github.com/williamspiro/HubSpot-Developer-Extension/issues/9
- [x] Remove dancing Corgis
- [x] Remove Google logos 
- [x] Take a few screenshots of extension for store listing(wait until all other milestone tasks are done)
- [x] write basic description of extension for store listing

**Comment by GonzaloTorreras** [comment]
Nooo!
I like the corgis dancing 🍡 .

**Comment by williamspiro** [comment]
I do too 😭 😄 but I do not know whom owns the rights to that gif 💩

**Comment by TheWebTech** [comment]
I wont be able to dedicate too much time to this over the weekend because I have family coming to town but, I think it'd be cool if we can get this into the chrome store by June 20th.

AJ Laporte and Matt Coley are doing a HubSpot Developers event near Chicago on the 20th.
http://chicago.hubspotusergroups.com/register-for-june-2018-hug-matt-coley-the-need-for-speed

If we got it into the chrome store by then I could promote it to the developers who show up

**Comment by GonzaloTorreras** [comment]
Hmm, we need to focus on the really basics if you wanna have that date.
I have a hard deadline on 21, so don't think I am going to have too much free hours this days.
can't promise anything!

**Comment by TheWebTech** [comment]
Well, we can easily get the corgi's atleast hidden, google logo swapped, a description, and atleast a temporary icon going. If we had to launch with the panda that wouldn't be the end of the world though it might be copyrighted or something.

**Comment by TheWebTech** [comment]
There I knocked out the description, feel free to edit it.

**Comment by TheWebTech** [comment]
There if @williamspiro approves this PR then we can knock out 2 more and we're down to just finding a new icon and taking screenshots. :)
https://github.com/williamspiro/HubSpot-Developer-Extension/pull/7

See - we can pull this off.

**Comment by TheWebTech** [comment]
Alrighty going to try to get some time to review the process for submitting to the chrome store.

@williamspiro Do you want to be the one to upload it or should I?

It'd be great if we could devise a way to always have the extension use the latest version of the Master Branch. but that's something that can be thought of down the road.

Just figure it'd be better than requiring one of us to manually upload the zip every time. Which creates a potential future bottleneck if one of us doesn't have time to do it or something.

**Comment by TheWebTech** [comment]
Sorry didn't wait for a response, wanted to get something up. 
https://chrome.google.com/webstore/detail/hubspot-developer-extensi/gebemkdecnlgbcanplbgdpcffpdnfdfo
